apiVersion: storage.k8s.io/v1
kind: StorageClass
metadata:
  name: ovirt-csi-sc
provisioner: ovirt-csi-driver
volumeBindingMode: Immediate 
parameters:
  ovirtStoraeStorageDomain: "nfs" 
  ovirtDiskThinProvisioning: "true"
  
