apiVersion: storage.k8s.io/v1
kind: StorageClass
metadata:
  name: ovirt-csi-sc
provisioner: csi.ovirt.org
annotations:
  storageclass.kubernetes.io/is-default-class: "true"
volumeBindingMode: Immediate 
parameters:
  ovirtStoraeStorageDomain: "nfs" 
  ovirtDiskThinProvisioning: "true"
  
