apiVersion: v1
kind: Namespace
metadata:
  name: ovirt-csi-driver
---
apiVersion: v1
kind: ServiceAccount
metadata:
  name: ovirt-csi-node-sa
  namespace: ovirt-csi-driver
---
apiVersion: v1
kind: ServiceAccount
metadata:
  name: ovirt-csi-controller-sa
  namespace: ovirt-csi-driver
---
kind: ClusterRoleBinding
apiVersion: rbac.authorization.k8s.io/v1
metadata:
  name: ovirt-csi-controller-provisioner-binding
subjects:
  - kind: ServiceAccount
    name: ovirt-csi-controller-sa
    namespace: ovirt-csi-driver
roleRef:
  kind: ClusterRole
  name: system:csi-external-provisioner
  apiGroup: rbac.authorization.k8s.io
---
kind: ClusterRoleBinding
apiVersion: rbac.authorization.k8s.io/v1
metadata:
  name: ovirt-csi-controller-attacher-binding
subjects:
  - kind: ServiceAccount
    name: ovirt-csi-controller-sa
    namespace: ovirt-csi-driver
roleRef:
  kind: ClusterRole
  name: system:csi-external-attacher
  apiGroup: rbac.authorization.k8s.io
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: system:ovirt-csi-driver
rules:
  - apiGroups: [""]
    resources: ["persistentvolumes"]
    verbs: ["get", "list", "watch", "update", "create", "delete"]
  - apiGroups: [""]
    resources: ["persistentvolumeclaims"]
    verbs: ["get", "list", "watch", "update"]
  - apiGroups: ["storage.k8s.io"]
    resources: ["storageclasses"]
    verbs: ["get", "list", "watch"]
  - apiGroups: [""]
    resources: ["nodes"]
    verbs: ["get", "list", "watch", "update", "patch"]
  - apiGroups: ["csi.storage.k8s.io"]
    resources: ["csinodeinfos"]
    verbs: ["get", "list", "watch"]
  - apiGroups: ["storage.k8s.io"]
    resources: ["csinodes"]
    verbs: ["get", "list", "watch"]
  - apiGroups: ["storage.k8s.io"]
    resources: ["volumeattachments"]
    verbs: ["get", "list", "watch", "update"]
  - apiGroups: [""]
    resources: ["events"]
    verbs: ["list", "watch", "create", "update", "patch"]
  - apiGroups: ["security.openshift.io"]
    resources: ["securitycontextconstraints"]
    verbs: ["use"]
    resourceNames: ["privileged"]

---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: system:openshift:csi-driver-controller-leader-election
rules:
  - apiGroups: [""]
    resources: ["configmaps", "endpoints"]
    verbs: ["get", "list", "watch", "update", "create", "delete"]
---
kind: ClusterRoleBinding
apiVersion: rbac.authorization.k8s.io/v1
metadata:
  name: ovirt-csi-binding
subjects:
  - kind: ServiceAccount
    name: ovirt-csi-controller-sa
    namespace: ovirt-csi-driver
roleRef:
  kind: ClusterRole
  name: system:ovirt-csi-driver
  apiGroup: rbac.authorization.k8s.io
---
kind: ClusterRoleBinding
apiVersion: rbac.authorization.k8s.io/v1
metadata:
  name: ovirt-csi-binding-leader
subjects:
  - kind: ServiceAccount
    name: ovirt-csi-controller-sa
    namespace: ovirt-csi-driver
roleRef:
  kind: ClusterRole
  name: system:openshift:csi-driver-controller-leader-election
  apiGroup: rbac.authorization.k8s.io
---

